USE [master]
GO

/****** Object:  Database [BooksStore]    Script Date: 24/02/2022 12:38:46 ******/
CREATE DATABASE [BooksStore]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'BooksStore', FILENAME = N'C:\Users\roygi\BooksStore.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'BooksStore_log', FILENAME = N'C:\Users\roygi\BooksStore_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [BooksStore].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [BooksStore] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [BooksStore] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [BooksStore] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [BooksStore] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [BooksStore] SET ARITHABORT OFF 
GO

ALTER DATABASE [BooksStore] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [BooksStore] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [BooksStore] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [BooksStore] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [BooksStore] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [BooksStore] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [BooksStore] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [BooksStore] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [BooksStore] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [BooksStore] SET  DISABLE_BROKER 
GO

ALTER DATABASE [BooksStore] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [BooksStore] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [BooksStore] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [BooksStore] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [BooksStore] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [BooksStore] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [BooksStore] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [BooksStore] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [BooksStore] SET  MULTI_USER 
GO

ALTER DATABASE [BooksStore] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [BooksStore] SET DB_CHAINING OFF 
GO

ALTER DATABASE [BooksStore] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [BooksStore] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [BooksStore] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [BooksStore] SET QUERY_STORE = OFF
GO

USE [BooksStore]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE [BooksStore] SET  READ_WRITE 
GO

